**

!apps/web/Dockerfile
!apps/web/Dockerfile.dockerignore
!.npmrc
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!turbo.json
!tsconfig.json

!apps
!apps/web
!apps/web/**

!packages
!packages/db
!packages/db/**
!packages/errors
!packages/errors/**
!packages/services
!packages/services/**
!packages/types
!packages/types/**
!packages/ui
!packages/ui/**
!packages/utils
!packages/utils/**
