**

!apps/agent/Dockerfile
!apps/agent/Dockerfile.dockerignore
!.npmrc
!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!turbo.json
!tsconfig.json

!apps
!apps/agent
!apps/agent/**

!packages
!packages/db
!packages/db/**
!packages/errors
!packages/errors/**
!packages/services
!packages/services/**
!packages/types
!packages/types/**
!packages/utils
!packages/utils/**
